### ISSUE TITLE
Crashes Every time i click settlements 

### ISSUE THREAD

**Issue by Matthews2005** [Pingger/Empire-Mod#13]
I have 3 mods attached just the "Empires" , "Rim world at war" and " Harmony

**Comment by Pingger** [comment]
OK ... since I can't reproduce the issue, I need the following information:
1. Is this the "Rimworld at War" mod? https://steamcommunity.com/sharedfiles/filedetails/?id=2532632591
1. What is your exact mod loading order?
1. What is the excption thrown? (If unsure, attach the "Player.log", after the game crashes
1. Is this a new game since 1.3 or is this an old save from 1.2, that you are running in 1.3?
